# Generated by Django 4.2.6 on 2023-12-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='image',
        ),
    ]
