# Generated by Django 4.2.6 on 2023-12-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_remove_club_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.FileField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
