# Generated by Django 4.2.6 on 2023-12-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_event_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='staff_id',
        ),
    ]
